data:
  indist_train:
    batch_size: 128
    dataset: JetsIMG
    n_workers: 8
    path: /remote/gpu06/favaro/nae4hep/normalized-autoencoders/datasets/train.img40X40.crop.rot.flip.norm.sig.correct.h5
    shuffle: true
    size: 40
    split: training
  indist_val:
    batch_size: 128
    dataset: JetsIMG
    n_workers: 8
    path: /remote/gpu06/favaro/nae4hep/normalized-autoencoders/datasets/train.img40X40.crop.rot.flip.norm.sig.correct.h5
    size: 40
    split: validation
  ood_target:
    batch_size: 128
    channel: 1
    dataset: JetsIMG
    n_workers: 4
    path: /remote/gpu06/favaro/nae4hep/normalized-autoencoders/datasets/train.img40X40.crop.rot.flip.norm.bkg.correct.h5
    size: 40
    split: evaluation
  ood_val:
    batch_size: 128
    channel: 1
    dataset: JetsIMG
    n_workers: 4
    path: /remote/gpu06/favaro/nae4hep/normalized-autoencoders/datasets/train.img40X40.crop.rot.flip.norm.bkg.correct.h5
    size: 40
    split: validation
device: cuda:0
id: qcd_conv2fc
logger: nae
model:
  arch: nae
  decoder:
    activation: PReLU
    arch: deconvae
    batch_norm: false
    bias: true
    dropout: false
    nh: 8
    out_activation: PReLU
    spectral_norm: false
  encoder:
    activation: PReLU
    arch: convae
    batch_norm: false
    bias: true
    dropout: false
    nh: 8
    nh_mlp: 512
    out_activation: PReLU
    spectral_norm: false
  nae:
    buffer_size: 10000
    gamma: 1
    l2_norm_reg: 1.0e-11
    l2_norm_reg_en: 1.0e-11
    replay: true
    replay_ratio: 0.9
    sampling: on_manifold
    spherical: true
    temperature: 1
    temperature_trainable: false
    x_bound:
    - 0
    - 1
    x_clip_langevin_grad: 0.01
    x_cut: false
    x_noise_anneal: 1
    x_noise_std: 0.05
    x_norm: false
    x_step: 50
    x_stepsize: 100
    z_bound: null
    z_clip_langevin_grad: null
    z_cut: false
    z_noise_anneal: 0.1
    z_noise_std: 0.05
    z_norm: false
    z_step: 10
    z_stepsize: 0.2
  x_dim: 1
  z_dim: 8
seed: 22
trainer: nae
training:
  ae_epoch: 30
  ae_lr: 0.001
  fix_D: false
  mh: false
  nae_epoch: 50
  nae_lr: 1.0e-05
  print_interval: 250
  save_interval: 2000
  temperature_lr: 0.001
  val_interval: 250
